spring.application.name=fitai

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=${DB_URL}
spring.datasource.username={DB_USERNAME}
spring.datasource.password={DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}

# ======================
# Logging
# ======================
logging.level.jdbc=OFF
logging.level.jdbc.sqltiming=${SQL_TIMING_LOG:OFF}
logging.level.jdbc.resultsettable=${SQL_RESULT_LOG:OFF}
logging.level.org.springframework.security=${SECURITY_LOG_LEVEL:INFO}

# ======================
# External APIs
# ======================
openrouter.api.key=${OPENROUTER_API_KEY}
jwt.secret=${JWT_SECRET}
